### ISSUE TITLE
Compatibility with Drush 4?

### ISSUE THREAD

**Issue by rocketnova** [scor/dgb#4]
Hi,

It looks like dgb-dump isn't compatible with Drush 4. I'm using Drush 4.1. When I try to to do a dgb-commit or dgb-dump, I get a mysqldump error: "Warning: mysqldump: ignoring option '--databases' due to invalid value". This happens with both Drupal 6 and Drupal 7.

Any thoughts about what might be causing this incompatibility?

Cheers,
Michelle

**Comment by scor** [comment]
I haven't had time to look at Drush 4 yet, but I ought to fix that asap. Thanks for filing an issue, and of course feel free to submit a patch the github way... see also this related feature request http://drupal.org/node/698264

**Comment by scor** [comment]
fixed with https://github.com/scor/dgb/commit/5453f0d2e298730bfdb5430d51c4dbfb534bd27e

Thanks Michelle for reporting this bug.
