### ISSUE TITLE
drush 5 - dgb will require a drushrc.php in DRUPAL_ROOT

### ISSUE THREAD

**Issue by neostar** [scor/dgb#8]
In the README.txt it says "dgb will require a drushrc.php in DRUPAL_ROOT no matter what", but according to the Drush 5 documentation, Drush 5 doesn't look for a drushrc.php in DRUPAL_ROOT anymore. Could you please update the documentation accordingly? The alternative would be to put drushrc.php in sites/all/drush/drushrc.php

**Comment by scor** [comment]
You're right, I've updated the README.txt. note that drushrc.php is in fact not required for dgb to work now.
